Repository piotr-grosicki/project-jdp-2107-01, pull requests merged in 2021-08, with the labels that each got.

#41 Build-fix
  src/main/java/com/kodilla/ecommercee/product/repository/ProductDao.java
Labels: bug

#40 Jdp210701 36
  build.gradle
  src/main/java/com/kodilla/ecommercee/config/CoreConfiguration.java
  src/main/java/com/kodilla/ecommercee/user/domain/User.java
Labels: bug, for-review

#45 Create user without cart
  src/main/java/com/kodilla/ecommercee/user/domain/User.java
  src/main/java/com/kodilla/ecommercee/user/domain/UserDto.java
  src/main/java/com/kodilla/ecommercee/user/mapper/UserMapper.java
Labels: bug

#47 Update README.md
  README.md
Labels: documentation, for-review

#48 JDP210701-37 - add readme images
  src/main/resources/images/cart-controller.png
  src/main/resources/images/group-controller.png
  src/main/resources/images/models.png
  src/main/resources/images/order-controller.png
  src/main/resources/images/product-controller.png
  src/main/resources/images/user-controller.png
Labels: documentation, for-review

#50 Update README.md - add images
  README.md
Labels: documentation
